language: objective-c
osx_image: xcode8
script: 
  - xctool -workspace ./MusicNotation.xcworkspace -scheme MusicNotationKit build test -sdk macosx
after_success:
  - bash <(curl -s https://codecov.io/bash)
