# Generate code coverage metrics on the code in the music-notation swift package.

name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Coverage:
    runs-on: macos-latest

    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v2
      - name: Gather test coverage 
        run: swift test -c debug -Xswiftc -enable-testing --enable-code-coverage
      - name: Gather test coverage 
        run: xcrun llvm-cov export -summary-only -ignore-filename-regex MusicNotationTests .build/debug/music-notationPackageTests.xctest/Contents/MacOS/music-notationPackageTests -instr-profile .build/debug/codecov/default.profdata > .build/coverage.json
      - name: Get Coverage Total Percent  
        run: echo "COVERAGE=$(cat .build/coverage.json|jq '.data[0]["totals"]["lines"]["percent"]')" >> $GITHUB_ENV
      - name: Create The Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: e9c967d4e429f39f233c8e5f88d988cda82456b2
          filename: music-notation__main.json
          label: Coverage
          message: ${{ env.COVERAGE }}
          color: green
          namedLogo: jest

