# Generate code coverage metrics on the code in the music-notation swift package.

name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Coverage:
    runs-on: macos-latest

    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v2
      - name: Gather test coverage 
        run: swift test -Xswiftc -enable-testing --enable-code-coverage
      - name: Gather test coverage 
        run: xcrun llvm-cov export -summary-only -ignore-filename-regex MusicNotationTests .build/release/music-notationPackageTests.xctest/Contents/MacOS/music-notationPackageTests -instr-profile .build/release/codecov/default.profdata > .build/coverage.json
      - run: cat .build/coverage.json|jq '.data[0]["totals"]["lines"]["percent"]'; exit 0;
      - name: Create The Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: e9c967d4e429f39f233c8e5f88d988cda82456b2
          filename: music-notation__${{ env.BRANCH }}.json
          label: Coverage
          message: 42
          color: green
          namedLogo: jest

