name: music-notation-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    strategy:
      matrix:
        xcode_version: ['12.4']
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test

# Comment out for now. Can't seem to get this to work. Later.
#  linux:
#    strategy:
#      matrix:
#        tag: ['5.3']
#    runs-on: ubuntu-latest
#    container:
#      image: swift:${{ matrix.tag }}
#    steps:
#    - uses: actions/checkout@v2
#    - name: Build
#      run: swift test -c release -Xswiftc -enable-testing
#
